### ISSUE TITLE
Generate/document list of object/concepts being used by each repository

### ISSUE THREAD

**Issue by bcorrie** [airr-knowledge/issues#12]
- [x] ADC
- [x] IEDB
- [x] VDJBase
- [x] OGRDB
- [x] IRAD

**Comment by bcorrie** [comment]
List in `Object/Relation Alignment` google sheet.

**Comment by bcorrie** [comment]
ADC Objects are listed in the google sheet.

**Comment by schristley** [comment]
We have the primary objects from each repository, so I think that's sufficient for the purpose of this task. We still have some work to discuss/design any new objects but that will be part of the creating the common data model.
