### ISSUE TITLE
Generate/document list of current curation/extraction/annotation processes for each repository

### ISSUE THREAD

**Issue by schristley** [airr-knowledge/issues#13]
- [x] IEDB
- [x] IRAD
- [x] OGRDB
- [x] VDJbase
- [x] iReceptor
- [x] VDJServer

**Comment by schristley** [comment]
Hi @jamesaoverton , please write up a document for IEDB and put in google drive. Assign to other IEDB folks if they are better. It isn't meant to be an all-inclusive list, instead it's the ones where we state: "These processes will be enhanced
to incorporate the ontologies, standards, and CDM." More detail in #7

**Comment by jamesaoverton** [comment]
I drafted a "IEDB validation and automation" this morning, in the Google Drive.

**Comment by schristley** [comment]
IRAD has no formalized curation/extraction/annotation processes as of yet.

**Comment by schristley** [comment]
VDJServer document in google drive
