### ISSUE TITLE
Generate/document list of automation needs for each repository

### ISSUE THREAD

**Issue by schristley** [airr-knowledge/issues#14]
- [x] IEDB
- [x] IRAD
- [x] OGRDB
- [x] VDJbase
- [x] iReceptor
- [x] VDJServer

**Comment by schristley** [comment]
Hi @jamesaoverton , and related to #13 , we want to list those processes that require/desire automation. Please write up a list for IEDB.

**Comment by jamesaoverton** [comment]
I drafted a "IEDB validation and automation" this morning, in the Google Drive. I'm happy to go into more detail as needed.

**Comment by schristley** [comment]
VDJServer document in google drive

**Comment by schristley** [comment]
IRAD doesn't have any automation processes
