### ISSUE TITLE
Generate/document list of relations being used by each repository

### ISSUE THREAD

**Issue by bcorrie** [airr-knowledge/issues#17]
- [x] AIRR
- [x] IEDB
- [x] VDJBase
- [x] OGRDB
- [x] IRAD

**Comment by bcorrie** [comment]
I am not sure we need to do this in its entirety, but I created this issue to track what we decided to do and what the outcome was. 

I suggest we use the MIRO board for this.

I have added in the AIRR relationships up to a certain level of granularity - @schristley if you have time it would be good to have you review those. It is a bit complicated as I wanted to try and capture the study/subject/sample hierarchy, but in a way that is orthogonal to the `Repertoire` view that we typically use in the ADC.

**Comment by schristley** [comment]
> I am not sure we need to do this in its entirety, but I created this issue to track what we decided to do and what the outcome was.
> 
> I suggest we use the MIRO board for this.
> 
> I have added in the AIRR relationships up to a certain level of granularity - @schristley if you have time it would be good to have you review those. It is a bit complicated as I wanted to try and capture the study/subject/sample hierarchy, but in a way that is orthogonal to the `Repertoire` view that we typically use in the ADC.

Thanks @bcorrie , that looks great! I also see that you already started a few conventions with a legend and color coding, which is good because we will need more...

MIRO is good for prototyping, but we will still need a spreadsheet with a list. That's because relations will have additional properties/attributes just like objects, and those are easier to list on spreadsheet. Right now that's cardinality and an ontology term, but we might add more.

**Comment by schristley** [comment]
@williamdlees I added a couple of boxes for germlines and genotypes to the miro diagram, please review!

**Comment by schristley** [comment]
> I suggest we use the MIRO board for this.

@bcorrie just to be pedantic cuz that's how I am sometimes ;-) What we are doing on miro is essentially the last bullet item in #9 . Like all good humans we race forward to the best part :-D

> I have added in the AIRR relationships up to a certain level of granularity - @schristley if you have time it would be good to have you review those. It is a bit complicated as I wanted to try and capture the study/subject/sample hierarchy, but in a way that is orthogonal to the Repertoire view that we typically use in the ADC.

Great work. I've generalized what you started with the legend and added more stuff. I'm not sure if tagging `Repertoire` specially as a composite object (renamed from grouping) is useful? If so, we probably need to be more specific by what we mean, and does it apply to other objects.

The downstream annotated stuff like `Clone` and `Receptor` need more links to both the biology and the data processing

**Comment by bcorrie** [comment]
> > I suggest we use the MIRO board for this.
> 
> @bcorrie just to be pedantic cuz that's how I am sometimes ;-) What we are doing on miro is essentially the last bullet item in #9 . Like all good humans we race forward to the best part :-D

8-)

Yes, I agree, the real intent for the MIRO board is to go far beyond what this issue requires.

My suggestion to use MIRO for this was that it was the best place to represent relationships - and having the individual representations in the same document as our emerging unified model seemed like a plus 8-)

**Comment by bcorrie** [comment]
> Great work. I've generalized what you started with the legend and added more stuff. I'm not sure if tagging `Repertoire` specially as a composite object (renamed from grouping) is useful? If so, we probably need to be more specific by what we mean, and does it apply to other objects.

Cool... diagram is looking pretty "interesting" 8-)

**Comment by williamdlees** [comment]
VDJbase/OGRDB look good to me. I have extended it a little to help show the way that VDJbase determines allele usage in populations, which is used in turn to refine germline sets.

**Comment by schristley** [comment]
The miro board diagram has satisfied this for the most part
