### ISSUE TITLE
Overlap/alignment of fields between repositories

### ISSUE THREAD

**Issue by bcorrie** [airr-knowledge/issues#5]

**Comment by bcorrie** [comment]
In the "Consolidate Field Mapping" file I have color coded the different platforms by column so you can differentiate AIRR, IEDB, IRAD, VDJBase easily. I didn't color code the IEDB columns because they already have some color coding.

@rvita or @bpeters42 or someone from the IEDB team can you look at the IEDB columns and see if they align and capture the BCell TCell export that you have?

**Comment by schristley** [comment]
We've pushed this about as far as we need to go. With an AKC data model, it now becomes more important to align the schemas from each repository with AKC versus between repositories.
