### ISSUE TITLE
Generate/document list of ontologies being used by each repository

### ISSUE THREAD

**Issue by bcorrie** [airr-knowledge/issues#6]
- [x] ADC
- [x] IEDB
- [x] VDJBase
- [x] OGRDB
- [x] IRAD

**Comment by bcorrie** [comment]
I added a column in the `Consolidated Fields` that pulls out whether the AIRR Spec or IEDB treats a field as an ontology field and if so what ontology is used and if both AIRR and IEDB think it is an ontology whether the ontologies used are the same. 

Good news is that when both use ontologies, they appear to use the same ontology - yeah us 8-)

**Comment by bcorrie** [comment]
There are a couple of "Filter Views" in the spreadsheet that filter data based on ontology status in various forms.

**Comment by bcorrie** [comment]
In `Consolidate Field Mapping.xlsx` there is an Ontology column. It is populated currently for AIRR (Column AI) and IEDB (Column O) Ontology columns. I created VDJBase (Column F) and IRAD (Column I) ontology columns.

@bpeters42 @rvita do you consider Column O to be complete for IEDB? If so do you want to check the above box in the list.

@williamdlees similarly, for VDJBase can you look at Column F and check the ontology fields and if you feel they are up to date then check the list above for VDJBase and confirm that any fields that use ontologies are noted along with which ontologies. I suspect you map pretty closely (if not exactly) to the AIRR ontology terms. If so then you are done 8-)

@krishnaroskin @KevinABurns137 can you do the same for column I and confirm that any fields that use ontologies are noted along with which ontologies that are used.

I think this should be quick (???) and if so we can then close this issue.

**Comment by bcorrie** [comment]
@KevinABurns137 @krishnaroskin I see that you have already checked the box - thanks.

**Comment by bpeters42** [comment]
I checked the IEDB box - as I think the spirit of this is done. We might want to consider if we also want to capture non-ontology references to databases (e.g. Pubmed, UniProt), that have similar function. And I noted that some fields are missing from the alignment for the IEDB, e.g. 'process type' under 'in vivo process' - presumably because they only make sense in combination with other fields (Immunogen), which is aligned. I suspect/hope this will make much more sense when we do the field alignment within.

**Comment by williamdlees** [comment]
Confirmed that VDJbase uses the same ontologies as MiAIRR and no others.

 

William

**Comment by rvita** [comment]
regarding: do you consider Column O to be complete for IEDB? If so do you want to check the above box in the list.
As of now column O is up to date, but this is something we are always working on expanding and more ontologies will be added over time. I donot know what you mean by "check the above box in the list." - maybe someone else already checked that box for me?

**Comment by bcorrie** [comment]
@rvita yes, the box is checked... 8-) 

> As of now column O is up to date, but this is something we are always working on expanding and more ontologies will be added over time. I donot know what you mean by "check the above box in the list." - maybe someone else already checked that box for me?

Thanks, that is what I thought, and yes someone checked the box - so we are done 8-)

**Comment by bcorrie** [comment]
OK, looks like the ontology inventory is done, I closing this issue.
