### ISSUE TITLE
Assessment of curation/extraction/annotation processes from public archives (1.3A)

### ISSUE THREAD

**Issue by schristley** [airr-knowledge/issues#7]
- [x] #13
- [x] #14

Aim 1.3 Critical metric: the proportion of processes incorporating the interoperable standards and CDM;
proportion of data and knowledge that is compliant; number of compliance metrics reported in the dashboard.

Each repository has curation and annotation workflows for extracting data and metadata from public archives. These processes take raw data and transform it into structured, standardized, high-quality content augmented with annotations that increase its utility. For example, AIR sequences are annotated with antigen binding domains and IEDB performs homology analysis across epitopes. These are within-repository annotations. These processes will be enhanced
to incorporate the ontologies, standards, and CDM (Aims 1.1-1.2), laying the foundation for interoperability
between the component repositories and bringing significant additional benefits to curation accuracy.

**Comment by williamdlees** [comment]
I have added a document for VDJbase to the AIRR Knowledge folder covering 1.3A/1.4A, @schristley please take a look and let me know whether it's what you were expecting

**Comment by jamesaoverton** [comment]
I created an "IEDB validation and automation" document next to the one @williamdlees created.

**Comment by bcorrie** [comment]
I have also created one of these for iReceptor data curation processes
